### PR TITLE
renaming package

### PR DESCRIPTION
**Pull request by charliewilco**
need to merge this to re-register package to bower under a new name `jquery-fittext`

### CODE REVIEW

**Comment by davatron5000** [comment]
Thanks! This should clear up some of #143. Anything else needed to resolve that issue?

**Comment by charliewilco** [comment]
there's an issue with apparently title casing in the package name so i need to unregister the old package, register the new one and update the readme

**Comment by charliewilco** [comment]
working on it... 
tigerzord

**Comment by charliewilco** [comment]
@davatron5000 can you run the following: 

``` shell
bower login # use github credentials
bower register jquery-fittext https://github.com/davatron5000/FitText.js.git
```

getting a series of errors about the metadata and the duplicate package

**Comment by davatron5000** [comment]
```
bower resolve       https://github.com/davatron5000/FitText.js.git#*
bower checkout      jquery-fittext#v1.2.0
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower resolved      https://github.com/davatron5000/FitText.js.git#1.2.0
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue?
(Y/n? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
bower register      https://github.com/davatron5000/FitText.js.git
bower EDUPLICATE    Duplicate package
```

**Comment by davatron5000** [comment]
```
λ bower search fittext
Search results:
    fittext https://github.com/adactio/FitText.js.git
    tm.fittext https://github.com/twmulloy/fittext.git
    fittext-fork https://github.com/lucasfercunha/FitText.js.git
    FitText120 https://github.com/lucasfercunha/FitText.js.git
    ngFitText-Fix https://github.com/powange/ng-FitText.js.git
    gumby-fittext https://github.com/GumbyFramework/FitText.git
    ng-FitText.js https://github.com/patrickmarabeas/ng-FitText.js.git
    jquery-fittext https://github.com/DevOctopus/FitText.js.git
    RWD-FitText.js https://github.com/Milanowicz/FitText.js.git
    ngFitText https://github.com/patrickmarabeas/ng-FitText.js.git
    jquery-fittext.js https://github.com/davatron5000/FitText.js.git
    reactFitText https://github.com/patrickmarabeas/react-FitText.js.git
    ngFitTextDynamic https://github.com/sgtpepper43/ng-FitTextDynamic.git
    squeezetext https://github.com/joinbox/fittext.git
    jquery-squeezetext https://github.com/joinbox/fittext.git
```

Looks like it's being camp'd on. and `.js` in ours is invalid. womp womp.

**Comment by charliewilco** [comment]
that looks familiar. the invalid-meta data error is weird. because it's not invalid, it's following the rules specified.

**Comment by charliewilco** [comment]
@sheerun is there any light you could shed on this issue? not sure what to do at this point.

**Comment by sheerun** [comment]
Someone abandoned this package. I've unregistered it, so you can register it again.

**Comment by davatron5000** [comment]
🏁  MISSION ACCOMPLISHED 🏁

```
λ bower register jquery-fittext https://github.com/davatron5000/FitText.js.git
bower resolve       https://github.com/davatron5000/FitText.js.git#*
bower checkout      jquery-fittext#v1.2.0
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower resolved      https://github.com/davatron5000/FitText.js.git#1.2.0
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
bower register      https://github.com/davatron5000/FitText.js.git

Package jquery-fittext registered successfully!
All valid semver tags on https://github.com/davatron5000/FitText.js.git will be available as versions.
To publish a new version, just release a valid semver tag.

Run bower info jquery-fittext to list the available versions.
```

```
λ bower search fittext
Search results:

    fittext https://github.com/adactio/FitText.js.git
    tm.fittext https://github.com/twmulloy/fittext.git
    fittext-fork https://github.com/lucasfercunha/FitText.js.git
    FitText120 https://github.com/lucasfercunha/FitText.js.git
    ngFitText-Fix https://github.com/powange/ng-FitText.js.git
    gumby-fittext https://github.com/GumbyFramework/FitText.git
    ng-FitText.js https://github.com/patrickmarabeas/ng-FitText.js.git
    jquery-fittext https://github.com/davatron5000/FitText.js.git
    RWD-FitText.js https://github.com/Milanowicz/FitText.js.git
    ngFitText https://github.com/patrickmarabeas/ng-FitText.js.git
    jquery-fittext.js https://github.com/davatron5000/FitText.js.git
    reactFitText https://github.com/patrickmarabeas/react-FitText.js.git
    ngFitTextDynamic https://github.com/sgtpepper43/ng-FitTextDynamic.git
    squeezetext https://github.com/joinbox/fittext.git
    jquery-squeezetext https://github.com/joinbox/fittext.git
```

**Comment by charliewilco** [comment]
donald-glover-as-troy-on-community-thumbs-up

**Comment by CupOfTea696** [comment]
Got a version mismatch with bower now though:
`bower textfit#^2.3.1          mismatch Version declared in the json (2.1.1) is different than the resolved one (2.3.1)`

**Comment by davatron5000** [comment]
@cupoftea696 This repo is `jquery-fittext` in Bower. `textfit` is something different.

**Comment by CupOfTea696** [comment]
My bad, sorry :p

**Pull request merged**
